version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/:/initdb
      - postgres-course-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-course-data:
